[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge", "pytorch"]
name = "wicore-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = "*"
python = "==3.11"
pytorch = { version = ">=2.7.1,<3", channel = "conda-forge" }
torchvision = { version = ">=0.22.0,<0.23", channel = "conda-forge" }
torchaudio = { version = ">=2.7.1,<3", channel = "conda-forge" }
transformers = ">=4.53.3,<5"
accelerate = ">=1.9.0,<2"
fastapi = ">=0.115.14,<0.116"
uvicorn = ">=0.35.0,<0.36"
pydantic = ">=2.11.7,<3"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
psutil = ">=7.0.0,<8"
requests = ">=2.32.4,<3"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
